#+title: 10mm Lit Review
#+author: Andrew Sugarman
#+OPTIONS: tex:t
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{letterpaper, margin=1in}

* 3D Microscopy Imaging + Relevant Articles
** Yakovlev [[https://journals.iucr.org/s/issues/2022/02/00/mo5248/mo5248.pdf][5mm_system]]
- max discusses detector utility in terms of field of view:resolution ratios
  1. the 5mm detector has a fov:resolution ratio of 10000. The 10mm detector has an fov to resolution ratio of 14285.7
  2. some of the best commercial systems are listed in the clark article
     - a key advantage of our detector is that it can be utilized within a benchtop source. Not only do we eclipse commmercial benchtop machines but we also are able to use this detector within a laboratory setting with a benchtop xray source
- Detector specifications
  - most detectors use objective lenses w/up to 5mil pixels
    - obejective lens = optical element that gathers light and focuses rays to form a real image
  - CMOS sensors now offer over 100mil pixels but there are not sufficient objective lenses to maximize their capability
    - prototype 5mm detector system used a thermoelectrically cooled CMOS camera with 10k x 7.096k pixel format and 3.1um pixel size
      - the custom objective lens provided 6.2x magnification, with 0.6 or 0.75 num aperture
        - resolution across entire field is refraction?/diffraction limited with an aperture of 0.6
*** TODO provides the fov of a 4x microscope lens at the resolution of 40x objective (must include this equivalent comparison for 10mm detector)
** Munck mcconnell [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9325079/pdf/JMI-286-201.pdf][optical_mesoscale_imaging]]
Definitions:
Microscopic imaging: visualization of structures that cannot be seen by the naked eye
Confocal microscopy: special fluorescence microscopy
*** Mesoscale imaging
Optical mesoscale imaging is defined by the authors as a "rapidly developing field that allows the visualization of larger samples than is possible with standard light microscopy"
- between cell and organism resolution
- key ongoing questions in "mesoscale imaging" that they highlight are shortcomings in labelling, clearing, and handling samples, as well as penetrating deeper into tissues at high resolution while minimizing shadows and scattering
- the authors define samples that exceed later developmental stages and thus the classical miscroscopy domain as mesoscopic imaging tasks (between the microscopic and macroscopic scale)
- specimens of interest = xenopus, tadpoles, froglings, zebrafish, medaka, insect larvae, homo sapiens
- confocal microscopy - limited by imaging depth of approximately 150-200 micrometers
  - limited FOV
  - stitching images together introduces further complications to the resultant image on top of its computational burden
- oct = "optical ultrasound"
- Mesolens technology
  - primarily used for (but not restricted to) confocal microscopy
  - 3D imaging of objects up to 6mm in diameter *fov of 4x lens* and "up to 3mm thick" [seems different than company spec sheet but maybe I am looking in different spots]
  - boasts NA of 0.47, offers subcellular resolution throughout entire mm range
  - *Key drawbacks of Mesolens*
    - large FOV requires specific optical components
    - sampling large fields is slow
  - Lightsheet microscopy - perpendicular illumination and acquisition lenses
    - general problems with light-sheet are that there can be heterogenous illumination, and the sample preparation is reliant on tissue clearing and fluorescent staining
**** TODO include note that ct is capable of handling heterogenous materials with the advent of phase contrast imaging (should continue to improve)
- micro-CT is often referred to as "preclinical"
- on phase contrast imaging - there is evidence that micro-CT can be performed "label-free" (without fluorescent or contrast-enhancing markers)
**** TODO emph ct is isotropic
- imaging depth only diffraction limited*phase
**** key limitations
- for targeted imaging, homogenous staining is problematic due to the "diffusion barrier" formed by tissue
**** Mesolens company [[http://www.mesolens.com/product/][giantmicroscope]]
- NA of ~0.5, magnification of 4x, field size 5mm
- I believe it is for confocal microscopy
** ANL TXM De Andrade [[https://onlinelibrary.wiley.com/doi/10.1002/adma.202008653][txmsystem]]
- TXM = transmission electron microscope
- "noninvasive nanoscale imaging" - argonne published the use of zone plates to achieve sub-10nm resolution
- cite this for figure 1 and discuss advancements in high resolution imaging (very small pixel sizes but also restricted to very small regions of interest) - could use within a synchrotron introduction sectoin
** Mesolens Articles
- NA does not change with the frame size of the lens
*** Mcconnell [[https://onlinelibrary.wiley.com/doi/abs/10.1111/jmi.12693][mconnelmeso_drosoph]]
- problem - drosophila is small enough to be difficult to prepare for imaging, but large enough that it presents a challenge to modes of miscroscopy imaging
- the authors used the Mesolens system to capture an entire larva or adult drosoph via confocal microscopy with subcellular detail in all tissues
  - this requires fixation, staining, and clearing
*** Mcconnell 2 [[https://doi.org/10.7554/eLife.18659][mesolens_elife]]
- stitching and registration present difficulties
- appears to be anisotropic, but has made great improvements in the z dimension
** D.P. Clark [[https://pubmed.ncbi.nlm.nih.gov/34284331/][micro-CT_smallanimals]]
- micro-CT is "an analogue" of clinical CT with higher spatial resolution (voxel size <100um)
- micro-CT typically uses "flat panel" detector arrays
- commercially available systems offer high fields of view, but none offer these with pixel size as small as ours
  - our detector does not rely on synchrotron imaging - it can be utilized within a benchtop micro-CT apparaturs with a laboratory source
- resolution of ssEM is 500x better than diffraction limited light microscopy
  - volume of ssEM images ~ 2.4 terabytes at original resolution
** Hildebrand [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5594570/][serial_em]]
*** ssEM of larval zebrafish
Performed imaging of whole regions with higher resolution focused imaging
- 5-7 dpf fish - 310gb images
- 17,963 sections at 60nm thick each
  - sectioned through a mm-long region
- anterior quarter of a 5.5dpf zfish was captured at an anisotropic resolution of 56.4x56.4x60nm3 from 16000 sections
  - targeted reacquisition from 12.5k sections was performed with an 18.8x18.8x60nm3 resolution
**** Methods: two larval fish were sectioned
- larval zebrafish (5-7dpf) were mounted in low melting agarose
- images captured with a two-photon microscope for fluorescence (800nm) imaging (frames had 764x509um2 fov, 0.6x0.6x1um voxel size)
- electron microscopy imaging:
  had to embed in extra mouse tissue for stability
  sections were cut with a diamond knife and restarting was occasionally required
  each section was 60nm thick
  entire 5.5 dpf zebrafish brain was captured in 18000 sections
** Daetwyler [[https://www.nature.com/articles/s42003-023-04857-4][lightsheetreview]]
Definitions:
1. Nyquist sampling: theorem to prevent aliasing distortion - sample rate must be at least twice the frequency of the wave you are detecting (for example we are nyquist-limited [obeying nyquist sampling theorem] because we sample 2x the rate of the frequency of blue light emitted by the scintillator)
2. Numerical aperture: (NA)=nsin(mu) where n is the refractive index of air and mu is the one half angular aperture [[https://www.microscopyu.com/microscopy-basics/numerical-aperture][nikon_microscopybasics]]
   - higher is better? so ours is better than the mesolens?
Notes:
- light sheet microscopy traditionally relies on orthogonal arrangement of illumination and detection
  - axial resolution of the image is limited by the thickness of the light-sheet (illumination)
Key limitations:
1. imaging large specimens at high resolution with light-sheet is impractical due to nyquist sampling
2. There is also a "temporal imaging barrier" (this may be less relevant to us than tissue clearing limitation given that we present no experiments with evolving samples)
- Overall there is a tradeoff between sample health, temporal + spatial resolution, and field of view
*** TODO Include sample health in discussion of microscopy imaging tradeoffs
*** TODO Identify whether our numerical aperture is comparable to, and if so better than the "mesolens" of confocal
- I suppose that it is given that the NA is a dimensionless number
*** Numerical aperture equations
The wider the numerical aperture (NA), the larger the range of angles captured by the detector system.
\begin{equation}
(NA) = nsin(\alpha)
\end{equation}
Where n = refractive index of the medium between the objective lens and the specimen, and $\alpha$ = 1/2 angular aperture of the objective, or "the half-angle of the maximum cone of light that can enter the or exit the lens".
*** Beer-Lambert law
- loss of light intensity as it propagates through a medium ~ I*(path_length)
  - [[https://en.wikipedia.org/wiki/Beer%E2%80%93Lambert_law][wiki]]
\begin{equation}
A = \epsilon * C * L
\end{equation}
- Where A = absorbance, epsilon = molar extinction coefficient, C = concentration of absorbing material, and L = length of light passing through the material
** Glaser [[https://www.nature.com/articles/s41592-022-01468-5][OTLS]]
Relies on tissue clearing
*** Tissue Clearing
Chemical treatment that effectively homogenizes the refractive indices of the materials within a tissue sample leading to near-transparency. For example, benzyl alcohol and benzyl benzoate were originally used to clear samples for light sheet fluorescence microscopy.
** Peng optical microscopy [[https://www.nature.com/articles/ncomms14836][BaSiC]]
- optical microscopy imaging is often hampered by shading or vignetting
- Peng et al developed an image correction tool to correct uneven illumination and improve stitching/mosaic quality
  - works quickly on a standard laptop
*** Optical microscopy - micron and sub-micron imaging
** sheikhzadeh [[https://pubmed.ncbi.nlm.nih.gov/30528631/][effectivepixsize]]
** Bissinger [[https://pubmed.ncbi.nlm.nih.gov/27880788/][bone-regeneration]]
** brunet, tafforeau [[https://pubmed.ncbi.nlm.nih.gov/36859614/][largebiologicalsamples_protocol]]
** mittone [[https://journals.iucr.org/s/issues/2017/06/00/mo5164/mo5164.pdf][sCMOShighres]]
** Sellerer [[https://pubmed.ncbi.nlm.nih.gov/31314812/][dualenergy_photoncounting]]

* Micro-CT math
Generally, detectors have limited resolution leading to contrast loss when generating an image from a real object. The modulation transfer function (MTF) measures the amount of contrast that is retained by a detector.
** Fourier transform [[https://www.youtube.com/watch?v=mkGsMWi_j4Q][good_youtube]]
** Resolution and MTF [[https://howradiologyworks.com/x-ray-resolution/][radsref]]:
- PSF = point spread function = image of an object
- LSF = line spread function = radial average of PSF
- MTF = modulation transfer function = fourier transform of the LSF
* Otherwise interesting
** Bhartiya [[][phase_hela]]

* Notes
** outlines and outtakes
*** Intro
Micro-computed tomography (micro-CT) is a transformative technology that has provided scientists the unique capability to generate high-resolution 3D images without destruction of the sample.
- The general method of micro-CT encompasses approaches to imaging that involve irradiating a rotating sample with x-rays as 2D radiographs termed ``projections'' are captured by a detector or camera system. These projections are then computationally reconstructed to form a 3D image volume with isotropic resolution that is dependent on the detector system used. Detector systems for x-ray imaging are commonly compared by the combination of their field of view (FOV) and pixel size. FOV is typically reported as a mm x mm dimension, and is significant in that it governs the size of the projections that can be recorded during image acquisition. The size of the pixels spanning an FOV govern the voxel size and ultimately the resolution of the resultant image. \underline{The utility of a micro-CT system in answering scientific questions is constrained by this ratio.}
- The status quo of micro-CT detector systems faces a trade-off between resolution and FOV.  Micro-CT detectors commonly offer pixel sizes smaller than 1 micron, but these are typically limited to a field of view (FOV) < 2mm x 2mm. This presents several key challenges to scientists who investigate samples that approach the centimeter scale in length.
- Applications of micro-CT and the need for mesoscale imaging:
(there is a need for whole-organism phenotyping [this detector expands on Yifu paper and not just maxs], 3D histopathology will require whole-biopsy imaging)
- Imaging whole specimens with isotropic resolution at the micron scale has led to key developments across a diverse array of scientific disciplines. For example, micro-CT has long been used in materials science, where researchers leverage high resolution 3D imaging to evaluate material fidelity in aerospace and aviation engineering*.
The Cheng Lab has previously leveraged synchrotron micro-CT for whole organism phenotyping (Ding 2019, Katz 2021). We more recently demonstrated the computer vision applications of high-resolution 3D images(Yakovlev 2023).
** Ongoing questions + supplemental ideas
*** Inclusion of images acquired by 5mm detector
**** TODO Is it reasonable to include unstained images (such as melanoma) acquired on the 5mm system as supplementary figures?
- this would be to state as an update that we believe these detectors also produce promising results for phase contrast imaging
